install.packages("naniar")
install.packages("report")
install.packages("tidyverse")
install.packages("dplyr")
install.packages("Matrix")
install.packages("lme4")
install.packages("lmerTest")
install.packages("ggplot2")

library(naniar)
library(report)
library(tidyverse)
library(dplyr)
library(Matrix)
library(lme4)
library(lmerTest)
library(ggplot2)
